
gpu-6th: phi-GPU.cpp hermite6-gpu.o
	mpicxx -Wall -fopenmp -O3 -DSIXTH -DGPU -I /usr/local/cuda/include -L /usr/local/cuda/lib -lcudart -o phi-GPU.exe $^

gpu-6th.s: phi-GPU.cpp hermite6-gpu.o
	mpicxx -Wall -S -fopenmp -O3 -DSIXTH -DGPU -I /usr/local/cuda/include -L /usr/local/cuda/lib -lcudart -o $@ $^

hermite6-gpu.o: hermite6-gpu.cu hermite6-gpu.h
	/usr/local/cuda/bin/nvcc -I /usr/local/cuda_sdk/common/inc  --host-compilation c++ -Xcompiler "-O3" -c $<

cubin: hermite6-gpu.cu
	/usr/local/cuda/bin/nvcc --host-compilation c++ -Xcompiler "-O3" -cubin $<
